### ISSUE TITLE
License

### ISSUE THREAD

**Issue by d4l3k** [btracey/gaussproc#1]
Hey,

I've run into a problem that I need a Gaussian process solver for. Would you consider licensing this code under MIT/BSD so others could use it as a base?

Thanks!

**Comment by btracey** [comment]
I added a license file and updated from my local directory.

Feel free to use this as a base, but please don't blindly trust the code. It's been a while since I used it, and it's not unlikely I made some hacks to finish some results. The code is also not stable at all. I will likely return to this repository in the near future, and I reserve rights to break everything.

That said, if you want to take this and build something great, please do, or if there are small fixes I could probably accept PRs.

**Comment by d4l3k** [comment]
Thanks! I mostly was using it as a base to understand how the mathematical notion maps to actual code since they're kind of different. 

I'm currently working on a similar library that's more up to date
